<?php

namespace Mozcu\MozcuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository {
    
    public function findAllPaginated($page, $cant) {
        $dql  = "SELECT a FROM MozcuMozcuBundle:Album a WHERE a.isActive = 1 ORDER BY a.downloads DESC";
        $query = $this->getEntityManager()->createQuery($dql);
        
        $query->setFirstResult($page * $cant)
            ->setMaxResults($cant);
        
        return $query->getResult();
    }
    
    public function findByProfile(Profile $profile) {
        $dql  = "SELECT a FROM MozcuMozcuBundle:Album a WHERE a.profile = :profileId ORDER BY a.releaseDate DESC";
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('profileId', $profile->getId());
        return $query->getResult();
    }
    
    public function findByTags(array $tags, $page = 0, $cant = 16) {
        $in = "(" . implode(',', $tags) . ")";
        //$cant = count($tags);
        
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $queryBuilder->select("a");
        $queryBuilder->from('MozcuMozcuBundle:Album', 'a');
        $queryBuilder->innerJoin('a.tags', 't');
        $queryBuilder->where("t.id IN {$in} AND a.isActive = 1");
        //$queryBuilder->groupBy("a.name");
        //$queryBuilder->having("COUNT(t.id) = {$cant}");
        $queryBuilder->orderBy('a.id', 'DESC');

        $query = $queryBuilder->getQuery();
        $query->setFirstResult($page * $cant)
              ->setMaxResults($cant);
        
        return $query->getResult();
    }
    
    public function liveSearch($name, $limit = 4) {
        $dql = "FROM MozcuMozcuBundle:Album a
                WHERE (a.name LIKE '%$name%' OR a.artist_name LIKE '%$name%') AND a.isActive = 1";
        
        if($limit > 0) {
            $dql = "SELECT a " . $dql;
            $query = $this->getEntityManager()->createQuery($dql);
            $query->setFirstResult(0)->setMaxResults($limit);
        } else {
            $dql = "SELECT COUNT(a.id) " . $dql;
            $query = $this->getEntityManager()->createQuery($dql);
            return $query->getSingleScalarResult();
        }
        
        return $query->getResult();
    }
    
    public function searchTotalCount($query) {
        return $this->liveSearch($query, 0);
    }
    
    public function findRelated(Album $album) {
        $tags = array();
        foreach($album->getTags() as $tag) {
            $tags[] = $tag->getId();
        }
        $in = "(" . implode(',', $tags) . ")";
        
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $queryBuilder->select("a, COUNT(t.id) as tagsCant");
        $queryBuilder->from('MozcuMozcuBundle:Album', 'a');
        $queryBuilder->innerJoin('a.tags', 't');
        $queryBuilder->where("t.id IN {$in} AND a.id <> {$album->getId()} AND a.isActive = 1");
        $queryBuilder->groupBy('a.id');
        $queryBuilder->orderBy('tagsCant', 'DESC');
        
        $query = $queryBuilder->getQuery()
                       ->setFirstResult(0)
                       ->setMaxResults(15);

        $results = $query->getResult();
        
        return array_map(
            function ($result) { return $result[0]; },
            $results
        );
    }
}
