<?php

namespace Mozcu\MozcuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
    public function liveSearchByName($name) {
        $dql = "SELECT p FROM MozcuMozcuBundle:Profile p JOIN p.user u
                WHERE p.name LIKE '%$name%' OR u.username LIKE '%$name%'";
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
}
