<?php

namespace Mozcu\MozcuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function liveSearchByName($name) {
        $dql  = "SELECT t FROM MozcuMozcuBundle:Tag t WHERE  t.name LIKE '%$name%'";
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
    
    public function getTagsPaginated($page, $limit) {
        $dql = "SELECT t FROM MozcuMozcuBundle:Tag t ORDER BY t.id DESC";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setFirstResult($page)->setMaxResults($limit);
        return $query->getResult();
    }
}
