parameters:
    image_presentation.album_list_thumbnail_size:
      name: 'list_thumbanil'
      width: 234
      height: 234
      thumbnail: true
    image_presentation.album_header_size:
      name: 'album_header'
      width: 155
      height: 155
    image_presentation.album_file_size:
      name: 'cover'
      width: 500
      height: 500
    image_presentation.profile_header_size:
      name: 'profile_header'
      width: 130
      height: 130
    image_presentation.profile_thumbnail_size:
      name: 'profile_thumbnail'
      width: 25
      height: 25
    image_presentation.livesearch_size:
      name: 'livesearch'
      width: 68
      height: 68
      
    default_profile_image:      'images/profile_125x125.jpg'
    default_profile_image_mini: 'images/profile_25x25.jpg'
    default_profile_image_live: 'images/profile_25x25.jpg'
    
    uploads.valid_song_types: ['audio/mpeg', 'audio/mpeg3', 'audio/x-mpeg-3', 'video/mpeg', 'video/x-mpeg', 'application/octet-stream']
    uploads.valid_image_types: ['image/jpeg', 'image/pjpeg', 'image/png']