### Authentication ###
login_check:
    pattern:   /login_check
MozcuMozcuBundle_logout:
    pattern:   /logout

### Home Controller ###
MozcuMozcuBundle_home:
  pattern: /
  defaults: { _controller: MozcuMozcuBundle:Home:index}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_ajaxGetHome:
  pattern: /ajaxGetHome
  defaults: { _controller: MozcuMozcuBundle:Home:ajaxGetHome}
  requirements:
        _method:  GET

MozcuMozcuBundle_register:
  pattern: /home/register
  defaults: { _controller: MozcuMozcuBundle:Home:register}
  requirements:
        _method:  POST
        
MozcuMozcuBundle_login:
  pattern: /login
  defaults: { _controller: MozcuMozcuBundle:Home:login}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_loadUserBar:
  pattern: /loadUserBar
  defaults: { _controller: MozcuMozcuBundle:Home:loadUserBar}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_loadLeftBar:
  pattern: /loadLeftBar
  defaults: { _controller: MozcuMozcuBundle:Home:loadLeftBar}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_ajaxLiveSearch:
    pattern: /liveSearch
    defaults: { _controller: MozcuMozcuBundle:Home:ajaxLiveSearch}
    requirements:
        _method: GET
        
MozcuMozcuBundle_searchResult:
    pattern: /search?query={query};
    defaults: { _controller: MozcuMozcuBundle:Home:search}
    requirements:
        _method: GET
        
MozcuMozcuBundle_about:
    pattern: /about
    defaults: { _controller: MozcuMozcuBundle:Home:about}
    requirements:
        _method: GET
        
MozcuMozcuBundle_terms:
    pattern: /terms
    defaults: { _controller: MozcuMozcuBundle:Home:terms}
    requirements:
        _method: GET

### Album Controller ###
MozcuMozcuBundle_albums:
    pattern: /albums
    defaults: {_controller: MozcuMozcuBundle:Album:index}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumsNextPage:
    pattern: /albums/page/{page}
    defaults: {_controller: MozcuMozcuBundle:Album:nextPage}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumsTag:
    pattern: /albums/tag/{tag}
    defaults: {_controller: MozcuMozcuBundle:Album:index}
    requirements:
      _method: GET
      
MozcuMozcuBundle_getTagsLive:
  pattern: /album/getTags
  defaults: {_controller: MozcuMozcuBundle:Album:getTagsLive}
  requirements:
    _method: GET
    
MozcuMozcuBundle_getTagsPaginated:
  pattern: /album/getTagsPaginated/{page}
  defaults: {_controller: MozcuMozcuBundle:Album:getTagsPaginated}
  requirements:
    _method: GET

MozcuMozcuBundle_findAlbumsByTags:
  pattern: /album/findAlbumsByTags
  defaults: {_controller: MozcuMozcuBundle:Album:findAlbumsByTags}
  requirements:
    _method: POST
    
MozcuMozcuBundle_getAlbumForPlayer:
  pattern: /album/getAlbumForPlayer
  defaults: {_controller: MozcuMozcuBundle:Album:getAlbumForPlayer}
  requirements:
    _method: GET

MozcuMozcuBundle_albumReportModal:
    pattern: /album/{id}/report
    defaults: {_controller: MozcuMozcuBundle:Album:albumReportModal}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumSubmitReport:
    pattern: /album/{id}/report
    defaults: {_controller: MozcuMozcuBundle:Album:albumSubmitReport}
    requirements:
      _method: POST
    
MozcuMozcuBundle_albumDownloadModal:
    pattern: /album/{id}/download
    defaults: {_controller: MozcuMozcuBundle:Album:albumDownloadModal}
    requirements:
      _method: GET

MozcuMozcuBundle_albumCheckout:
    pattern: /album/{id}/checkout
    defaults: {_controller: MozcuMozcuBundle:Album:albumCheckout}
    requirements:
      _method: GET

MozcuMozcuBundle_deleteAlbum:
    pattern: /albums/delete
    defaults: {_controller: MozcuMozcuBundle:Album:deleteAlbum}
    requirements:
      _method: POST
      
MozcuMozcuBundle_editAlbum:
    pattern: /albums/edit/{id}
    defaults: {_controller: MozcuMozcuBundle:Album:editAlbum}
    requirements:
      _method: GET
      
MozcuMozcuBundle_updateAlbum:
    pattern: /albums/update/{id}
    defaults: {_controller: MozcuMozcuBundle:Album:updateAlbum}
    requirements:
      _method: POST

MozcuMozcuBundle_albumAlbum:
    pattern: /{username}/album/{id}
    defaults: {_controller: MozcuMozcuBundle:Album:album}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumAlbumInformation:
    pattern: /{username}/album/{id}/information
    defaults: {_controller: MozcuMozcuBundle:Album:albumInformation}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumAlbumRelated:
    pattern: /{username}/album/{id}/related
    defaults: {_controller: MozcuMozcuBundle:Album:albumsRelated}
    requirements:
      _method: GET

MozcuMozcuBundle_albumAlbumPlaylist:
    pattern: /{username}/album/{id}/playlist
    defaults: {_controller: MozcuMozcuBundle:Album:albumPlaylist}
    requirements:
      _method: GET

### Upload Album Controller ###
MozcuMozcuBundle_uploadAlbumIndex:
  pattern: /albums/upload
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:index}
  requirements:
    _method: GET

MozcuMozcuBundle_uploadSong:
  pattern: /albums/upload/uploadSong
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:uploadSong}
  requirements:
    _method: POST
    
MozcuMozcuBundle_uploadImage:
  pattern: /albums/upload/uploadImage
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:uploadImage}
  requirements:
    _method: POST
    
MozcuMozcuBundle_getUploadedSongTemplate:
  pattern: /albums/upload/getUploadedSongTemplate
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:getUploadedSongTemplate}
  requirements:
    _method: GET
    
MozcuMozcuBundle_uploadAlbum:
  pattern: /albums/upload/uploadAlbum
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:uploadAlbum}
  requirements:
    _method: POST

### Profile Controller ###
MozcuMozcuBundle_accountConfigureProfile:
  pattern: /user/account/accountProfile
  defaults: {_controller: MozcuMozcuBundle:Profile:accountConfigProfile}
  requirements:
    _method: GET
    
MozcuMozcuBundle_accountConfigureUser:
  pattern: /user/account/accountUser
  defaults: {_controller: MozcuMozcuBundle:Profile:accountConfigUser}
  requirements:
    _method: GET

MozcuMozcuBundle_configureProfile:
  pattern: /user/account/profile
  defaults: {_controller: MozcuMozcuBundle:Profile:configProfile}
  requirements:
    _method: GET
    
MozcuMozcuBundle_configureUser:
  pattern: /user/account/user
  defaults: {_controller: MozcuMozcuBundle:Profile:configUser}
  requirements:
    _method: GET
    
MozcuMozcuBundle_saveUserSettings:
  pattern: /user/account/saveUserSettings
  defaults: {_controller: MozcuMozcuBundle:Profile:saveUserSettings}
  requirements:
    _method: POST
    
MozcuMozcuBundle_saveProfileSettings:
  pattern: /user/account/saveProfileSettings
  defaults: {_controller: MozcuMozcuBundle:Profile:saveProfileSettings}
  requirements:
    _method: POST

MozcuMozcuBundle_profile:
  pattern: /{username}
  defaults: { _controller: MozcuMozcuBundle:Profile:index}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_profileBiography:
  pattern: /{username}/biography
  defaults: { _controller: MozcuMozcuBundle:Profile:biography}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_profileAlbums:
  pattern: /{username}/albums
  defaults: {_controller: MozcuMozcuBundle:Profile:albums}
  requirements:
    _method: GET

MozcuMozcuBundle_profilePlaylists:
  pattern: /{username}/playlists
  defaults: {_controller: MozcuMozcuBundle:Profile:playlists}
  requirements:
    _method: GET

MozcuMozcuBundle_profileReviews:
  pattern: /{username}/reviews
  defaults: {_controller: MozcuMozcuBundle:Profile:reviews}
  requirements:
    _method: GET

MozcuMozcuBundle_profileFollowers:
  pattern: /{username}/followers
  defaults: {_controller: MozcuMozcuBundle:Profile:followers}
  requirements:
    _method: GET
  
MozcuMozcuBundle_albumsForProfile:
  pattern: /{username}/albumsForProfile
  defaults: {_controller: MozcuMozcuBundle:Profile:albumsForProfile}
  requirements:
    _method: GET