### Authentication ###
login_check:
    pattern:   /login_check

MozcuMozcuBundle_logout:
    pattern:   /logout

MozcuMozcuBundle_oldLoginCheck:
  pattern: /ajax/oldLoginCheck
  defaults: { _controller: MozcuMozcuBundle:Home:oldLoginCheck}
  requirements:
        _method:  POST

### Home Controller ###
MozcuMozcuBundle_home:
  pattern: /
  defaults: { _controller: MozcuMozcuBundle:Album:index}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_ajaxGetHome:
  pattern: /ajax/home
  defaults: { _controller: MozcuMozcuBundle:Home:ajaxGetHome}
  requirements:
        _method:  GET

MozcuMozcuBundle_getRegistration:
  pattern: /registration
  defaults: { _controller: MozcuMozcuBundle:Home:getRegistration}
  requirements:
      _method: GET
        
MozcuMozcuBundle_postRegistration:
  pattern: /registration
  defaults: { _controller: MozcuMozcuBundle:Home:postRegistration}
  requirements:
    _method:  POST
    
MozcuMozcuBundle_forgotPassword:
  pattern: /forgotPassword
  defaults: { _controller: MozcuMozcuBundle:Home:forgotPassword}
  requirements:
      _method: GET
      
MozcuMozcuBundle_sendPasswordEmail:
  pattern: /forgotPassword/email
  defaults: { _controller: MozcuMozcuBundle:Home:sendPasswordEmail}
  requirements:
      _method: POST
      
MozcuMozcuBundle_passwordRecovery:
  pattern: /passwordRecovery/{hash}
  defaults: { _controller: MozcuMozcuBundle:Home:passwordRecovery}
  requirements:
      _method: GET
      
MozcuMozcuBundle_createNewPassword:
  pattern: /passwordRecovery/{hash}
  defaults: { _controller: MozcuMozcuBundle:Home:createNewPassword}
  requirements:
      _method: POST
      
MozcuMozcuBundle_login:
  pattern: /login
  defaults: { _controller: MozcuMozcuBundle:Home:login}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_loadUserBar:
  pattern: /ajax/loadUserBar
  defaults: { _controller: MozcuMozcuBundle:Home:loadUserBar}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_loadLeftBar:
  pattern: /ajax/loadLeftBar
  defaults: { _controller: MozcuMozcuBundle:Home:loadLeftBar}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_ajaxLiveSearch:
    pattern: /ajax/liveSearch
    defaults: { _controller: MozcuMozcuBundle:Home:ajaxLiveSearch}
    requirements:
        _method: GET
        
MozcuMozcuBundle_searchResult:
    pattern: /search/query/{query}
    defaults: { _controller: MozcuMozcuBundle:Home:search}
    requirements:
        _method: GET
        
MozcuMozcuBundle_terms:
    pattern: /terms
    defaults: { _controller: MozcuMozcuBundle:Home:terms}
    requirements:
        _method: GET

MozcuMozcuBundle_about:
    pattern: /about
    defaults: { _controller: MozcuMozcuBundle:Home:about}
    requirements:
        _method: GET

### Album Controller ###
MozcuMozcuBundle_tagSearchResult:
    pattern: /search/tag/{tag}
    defaults: { _controller: MozcuMozcuBundle:Album:index}
    requirements:
        _method: GET

MozcuMozcuBundle_albums:
    pattern: /albums
    defaults: {_controller: MozcuMozcuBundle:Album:index}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumsNextPage:
    pattern: /albums/page/{page}
    defaults: {_controller: MozcuMozcuBundle:Album:nextPage}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumsLoadFilters:
    pattern: /ajax/albums/filters
    defaults: {_controller: MozcuMozcuBundle:Album:loadFilters}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumsTag:
    pattern: /albums/tag/{tag}
    defaults: {_controller: MozcuMozcuBundle:Album:index}
    requirements:
      _method: GET
      
MozcuMozcuBundle_getTagsLive:
  pattern: /album/getTags
  defaults: {_controller: MozcuMozcuBundle:Album:getTagsLive}
  requirements:
    _method: GET

MozcuMozcuBundle_findAlbumsByTags:
  pattern: /album/findAlbumsByTags
  defaults: {_controller: MozcuMozcuBundle:Album:findAlbumsByTags}
  requirements:
    _method: POST
    
MozcuMozcuBundle_getAlbumForPlayer:
  pattern: /album/getAlbumForPlayer
  defaults: {_controller: MozcuMozcuBundle:Album:getAlbumForPlayer}
  requirements:
    _method: GET

MozcuMozcuBundle_albumReportModal:
    pattern: /album/{id}/report
    defaults: {_controller: MozcuMozcuBundle:Album:albumReportModal}
    requirements:
      _method: GET

MozcuMozcuBundle_albumSubmitReport:
    pattern: /album/{id}/report
    defaults: {_controller: MozcuMozcuBundle:Album:albumSubmitReport}
    requirements:
      _method: POST

MozcuMozcuBundle_albumShareModal:
    pattern: /album/{id}/share
    defaults: {_controller: MozcuMozcuBundle:Album:albumShareModal}
    requirements:
      _method: GET
    
MozcuMozcuBundle_albumDownloadModal:
    pattern: /album/{id}/download
    defaults: {_controller: MozcuMozcuBundle:Album:albumDownloadModal}
    requirements:
      _method: GET

MozcuMozcuBundle_albumCheckout:
    pattern: /album/{id}/checkout?increaseCounter={increaseCounter}
    defaults: {_controller: MozcuMozcuBundle:Album:albumCheckout}
    requirements:
      _method: GET

MozcuMozcuBundle_deleteAlbum:
    pattern: /albums/delete
    defaults: {_controller: MozcuMozcuBundle:Album:deleteAlbum}
    requirements:
      _method: POST
      
MozcuMozcuBundle_editAlbum:
    pattern: /albums/edit/{id}
    defaults: {_controller: MozcuMozcuBundle:Album:editAlbum}
    requirements:
      _method: GET
      
MozcuMozcuBundle_updateAlbum:
    pattern: /albums/update/{id}
    defaults: {_controller: MozcuMozcuBundle:Album:updateAlbum}
    requirements:
      _method: POST

MozcuMozcuBundle_albumAlbum:
    pattern: /{username}/album/{slug}
    defaults: {_controller: MozcuMozcuBundle:Album:album}
    requirements:
      _method: GET
      
MozcuMozcuBundle_albumAlbumAction:
    pattern: /{username}/album/{slug}/{action}
    defaults: {_controller: MozcuMozcuBundle:Album:albumOption}
    requirements:
      _method: GET

MozcuMozcuBundle_albumCheckoutFromPaymentAction:
    pattern: /checkout/{checkoutId}
    defaults: {_controller: MozcuMozcuBundle:Album:checkOutFromPayment}
    requirements:
      _method: GET
      
### Upload Album Controller ###
MozcuMozcuBundle_uploadAlbumIndex:
  pattern: /albums/upload
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:index}
  requirements:
    _method: GET

MozcuMozcuBundle_uploadSong:
  pattern: /albums/upload/uploadSong
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:uploadSong}
  requirements:
    _method: POST
    
MozcuMozcuBundle_uploadImage:
  pattern: /albums/upload/uploadImage
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:uploadImage}
  requirements:
    _method: POST
    
MozcuMozcuBundle_getUploadedSongTemplate:
  pattern: /albums/upload/getUploadedSongTemplate
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:getUploadedSongTemplate}
  requirements:
    _method: GET
    
MozcuMozcuBundle_uploadAlbum:
  pattern: /albums/upload/uploadAlbum
  defaults: {_controller: MozcuMozcuBundle:UploadAlbum:uploadAlbum}
  requirements:
    _method: POST

### Payment ###
MozcuMozcuBundle_returnFromPayment:
  pattern: /payment/return/{service}/{checkoutId}
  defaults: {_controller: MozcuMozcuBundle:Payment:returnFromPayment}
  requirements:
    _method: GET
    
MozcuMozcuBundle_checkoutSetPrice:
  pattern: /ajax/payment/{checkoutId}/setPrice
  defaults: {_controller: MozcuMozcuBundle:Payment:ajaxSetCheckoutPrice}
  requirements:
   _method: POST
   
MozcuMozcuBundle_returnFroMPAuth:
  pattern: /payment/mp/auth/{profile}
  defaults: {_controller: MozcuMozcuBundle:Payment:returnFromMercadopagoAuth}
  requirements:
    _method: GET
    
MozcuMozcuBundle_MPCheckout:
  pattern: /payment/mp/checkout
  defaults: {_controller: MozcuMozcuBundle:Payment:mercadopagoCheckout}
  requirements:
    _method: POST
    
MozcuMozcuBundle_unlinkMP:
  pattern: /payment/mp/unlink
  defaults: {_controller: MozcuMozcuBundle:Payment:unlinkMercadopago}
  requirements:
    _method: POST

### Action Log Controller ###
MozcuMozcuBundle_logAlbum:
  pattern: /ajax/log/album
  defaults: {_controller: MozcuMozcuBundle:ActionLog:logAlbum}
  requirements:
    _method: POST

### Profile Controller ###
MozcuMozcuBundle_account:
  pattern: /account
  defaults: {_controller: MozcuMozcuBundle:Profile:account}
  requirements:
    _method: GET
    
MozcuMozcuBundle_saveAccount:
  pattern: /account
  defaults: {_controller: MozcuMozcuBundle:Profile:saveAccount}
  requirements:
    _method: POST
    
MozcuMozcuBundle_getCountries:
  pattern: /ajax/countries
  defaults: {_controller: MozcuMozcuBundle:Common:getCountries}
  requirements:
    _method: GET
    
MozcuMozcuBundle_getCities:
  pattern: /ajax/cities
  defaults: {_controller: MozcuMozcuBundle:Common:getCities}
  requirements:
    _method: GET
    
MozcuMozcuBundle_follow:
  pattern: /ajax/follow
  defaults: {_controller: MozcuMozcuBundle:Profile:follow}
  requirements:
    _method: POST
    
MozcuMozcuBundle_likeAlbum:
  pattern: /ajax/album/{albumId}/like
  defaults: {_controller: MozcuMozcuBundle:Profile:likeAlbum}
  requirements:
    _method: POST

MozcuMozcuBundle_profile:
  pattern: /{username}
  defaults: { _controller: MozcuMozcuBundle:Profile:index}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_profileBiography:
  pattern: /{username}/biography
  defaults: { _controller: MozcuMozcuBundle:Profile:biography}
  requirements:
        _method:  GET
        
MozcuMozcuBundle_profileAlbums:
  pattern: /{username}/albums
  defaults: {_controller: MozcuMozcuBundle:Profile:albums}
  requirements:
    _method: GET

MozcuMozcuBundle_profilePlaylists:
  pattern: /{username}/playlists
  defaults: {_controller: MozcuMozcuBundle:Profile:playlists}
  requirements:
    _method: GET

MozcuMozcuBundle_profileReviews:
  pattern: /{username}/reviews
  defaults: {_controller: MozcuMozcuBundle:Profile:reviews}
  requirements:
    _method: GET

MozcuMozcuBundle_profileFollowers:
  pattern: /{username}/followers
  defaults: {_controller: MozcuMozcuBundle:Profile:followers}
  requirements:
    _method: GET
    
MozcuMozcuBundle_profileFollowing:
  pattern: /{username}/following
  defaults: {_controller: MozcuMozcuBundle:Profile:followers}
  requirements:
    _method: GET
  
MozcuMozcuBundle_albumsForProfile:
  pattern: /{username}/albumsForProfile
  defaults: {_controller: MozcuMozcuBundle:Profile:albumsForProfile}
  requirements:
    _method: GET