#parameters:
#    mozcu_mozcu.user_service.class: Mozcu\MozcuBundle\Service\UserService

services:
  authentication_handler:
    class: Mozcu\MozcuBundle\Handler\AuthenticationHandler
    arguments:  
      router : "@router"
    tags:
      - { name: 'monolog.logger', channel: 'security' }
    
  mozcu_mozcu.memcached:
    class: Mozcu\MozcuBundle\Lib\MemcachedConnector
    arguments: ['%memcached%']
      
  mozcu_mozcu.google_storage:
    class: Mozcu\MozcuBundle\Lib\GoogleStorageService
    arguments: ['@mozcu_mozcu.google_api', '%google_api%']
      
  mozcu_mozcu.google_api:
    class: Mozcu\MozcuBundle\Lib\GoogleApiConnector
    arguments: ['%google_api%']
  
  mozcu_mozcu.user_service:
    class: Mozcu\MozcuBundle\Service\UserService
    arguments: ['@doctrine.orm.entity_manager', '@security.encoder_factory', '@security.context', '@validator', '%password_recovery_time%', '%invalid_usernames%']
  
  mozcu_mozcu.profile_service:
    class: Mozcu\MozcuBundle\Service\ProfileService
    arguments: ['@doctrine.orm.entity_manager', '@mozcu_mozcu.image_service', '@mozcu_mozcu.user_service', '@validator']
      
  mozcu_mozcu.album_service:
    class: Mozcu\MozcuBundle\Service\AlbumService
    arguments: ['@doctrine.orm.entity_manager', '@mozcu_mozcu.upload_service', '@mozcu_mozcu.image_service', '%uploads%', '%google_api%']
      
  mozcu_mozcu.upload_service:
    class: Mozcu\MozcuBundle\Service\UploadService
    arguments: ['@doctrine.orm.entity_manager', '@mozcu_mozcu.google_storage', '%uploads%']

  mozcu_mozcu.queue_service:
    class: Mozcu\MozcuBundle\Service\QueueService
    arguments: ['@doctrine.orm.entity_manager']
  
  mozcu_mozcu.image_service:
    class: Mozcu\MozcuBundle\Service\ImageService
    arguments: ['@doctrine.orm.entity_manager', '@mozcu_mozcu.upload_service', '%image_presentation%']
      
  mozcu_mozcu.doctrine.entity_listener_resolver:
    class: Mozcu\MozcuBundle\Doctrine\EntityListenerResolver
    arguments: [ "@service_container" ]
    
  mozcu_mozcu.entity_listener.user:
    class: Mozcu\MozcuBundle\Listener\AlbumListener
    arguments: [ "@doctrine.orm.entity_manager", "@mozcu_mozcu.queue_service" ]
    tags:
      -  { name: doctrine.entity_listener }
      
  mozcu_mozcu.email_service:
    class: Mozcu\MozcuBundle\Service\EmailService
    arguments: ["@mailer", "@templating", "%mail.noreply_address%"]
  
  mozcu_mozcu.mercado_pago_service:
    class: Mozcu\MozcuBundle\Service\PaymentMethod\MercadoPagoService
    arguments: [ "%mercadopago%", "@router" ]
    scope: request
    
  mozcu_mozcu.payment_service:
    class: Mozcu\MozcuBundle\Service\PaymentService
    arguments: [ "@doctrine.orm.entity_manager", "@doctrine_mongodb.odm.document_manager", "@session", "@mozcu_mozcu.mercado_pago_service" ]
    scope: request