<?php

namespace Mozcu\MozcuBundle\Repository\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends DocumentRepository
{
}