<?php

namespace Mozcu\MozcuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumUploadQueueFailedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumUploadQueueFailedRepository extends EntityRepository
{
}
