<?php

namespace Mozcu\MozcuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    /**
     * 
     * @param string $name
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    public function findByLikeName($name, $startWith = false) {
        $like = $startWith ? "$name%" : "%$name%" ;
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
                ->from("MozcuMozcuBundle:Country", "c")
                ->where("c.name LIKE :name")
                ->orderBy('c.name', 'ASC')
                ->setParameter('name', $like);
        
        $query = $qb->getQuery()
                ->setFirstResult(0)
                ->setMaxResults(10);
        
        return $query->getResult();
    }
}
